ImageUploadsWithLikesEF.Web/Models/ErrorViewModel.cs
namespace ImageUploadsWithLikesEF.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageUploadsWithLikesEF.Web/Models/HomePageViewModel.cs
using ImageUploadsWithLikesEF.Data;

namespace ImageUploadsWithLikesEF.Web.Models
{
    public class HomePageViewModel
    {
        public List<Image> Images { get; set; }
    }
}

ImageUploadsWithLikesEF.Web/Models/ViewImageViewModel.cs
using ImageUploadsWithLikesEF.Data;

namespace ImageUploadsWithLikesEF.Web.Models
{
    public class ViewImageViewModel
    {
        public Image Image { get; set; }
        public bool Alreadyliked { get; set; }
    }
}

ImageUploadsWithLikesEF.Web/Controllers/HomeController.cs
using ImageUploadsWithLikesEF.Data;
using ImageUploadsWithLikesEF.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Diagnostics;
using System.Text.Json;

namespace ImageUploadsWithLikesEF.Web.Controllers
{
    public class HomeController : Controller
    {
        private string _connectionString;
        public HomeController(IConfiguration configuration)
        {
            _connectionString=configuration.GetConnectionString("ConStr");
        }
        public IActionResult Index()
        {
            var repo = new ImageRepository(_connectionString);
            return View(new HomePageViewModel
            {
                Images=repo.GetImages()
            });


        }
        public IActionResult ViewImage(int id)
        {
            var repo = new ImageRepository(_connectionString);
            return View(new ViewImageViewModel
            {
                Image=repo.GetById(id),

             });


        }


        [HttpPost]
        public IActionResult Like(int id)
        {
            var repo = new ImageRepository(_connectionString);
            repo.LikeImage(id);
            return Redirect("/home/viewimage/");
        }

    }
}

ImageUploadsWithLikesEF.Web/Controllers/UploadController.cs
using ImageUploadsWithLikesEF.Data;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

namespace ImageUploadsWithLikesEF.Web.Controllers
{
    public class UploadController : Controller
    {
        private string _connectionString;
        private IWebHostEnvironment _environment;
        public UploadController(IWebHostEnvironment environment, IConfiguration configuration)
        {
            _environment = environment;
            _connectionString=configuration.GetConnectionString("ConStr");
        }
     
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upload(string title, IFormFile imageFile)
        {
            var fileName = $"{Guid.NewGuid()}{Path.GetExtension(imageFile.FileName)}";
            string fullPath = Path.Combine(_environment.WebRootPath, "uploads", fileName);
            using var stream = new FileStream(fullPath, FileMode.CreateNew);
            imageFile.CopyTo(stream);
            

            var image = new Image { Title=title, FileName=Path.Combine("uploads",fileName), UploadedAt=DateTime.Now };
            var repo = new ImageRepository(_connectionString);
            repo.AddImage(image);
            return Redirect("/");
        }
    }
}

ImageUploadsWithLikesEF.Web/Views/Home/Index.cshtml
@using ImageUploadsWithLikesEF.Data
@model HomePageViewModel
<div class="row">
    @foreach(Image image in Model.Images){
            <div class="col-md-8 offset-md-2">
        <div class="bg-light p-4 rounded shadow mb-3" style="margin-bottom: 20px; text-align: center;">
            <a href="/home/viewimage?id=@image.Id">
                <h3>@image.Title</h3>
                <h5>Uploaded at:@image.UploadedAt</h5>
                <img style="width: 400px;" src="@image.FileName" />
            </a>
        </div>
        
    </div>
    }
 
</div>
    

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="/js/site.js?v=BxFAw9RUJ1E4NycpKEjCNDeoSvr4RPHixdBq5wDnkeY"></script>

ImageUploadsWithLikesEF.Web/Views/Home/ViewImage.cshtml
@using ImageUploadsWithLikesEF.Data
@model ViewImageViewModel
<div class="row">
    <input type="hidden" id="image-id" value="@Model.Image.Id" />
    <div class="col-md-10 offset-md-1 bg-light p-4 rounded shadow">
        <h1>@Model.Image.Title</h1>
        <img src="/uploads/@Model.Image.FileName" style="width: 900px;" />
        <br />
        <br />
        <button id="like-button" class="btn btn-primary btn-lg">LIKE</button>                 Current Likes: <span id="likes-count">@Model.Image.Likes</span>
    </div>
</div>


   

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="/js/site.js?v=BxFAw9RUJ1E4NycpKEjCNDeoSvr4RPHixdBq5wDnkeY"></script>

@*<script src="/js/view-image.js"></script>*@
@section scripts{
    <script src="/js/like.js"></script>
}

ImageUploadsWithLikesEF.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImageUploadsWithLikesEF.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ImageUploadsWithLikesEF.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImageUploadsWithLikesEF.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Upload" asp-action="Index">Upload</a>
                        </li>
                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ImageUploadsWithLikesEF.Web/Views/Upload/Index.cshtml
<html lang="en">
<div b-gx69rlccnc class="container">
    <main b-gx69rlccnc role="main" class="pb-3">
        <div class="row">
            <div class="col-md-6 offset-md-3 bg-light p-4 rounded shadow mb-3">
                <form method="post" action="/Upload/upload" enctype="multipart/form-data">
                    <input type="text" class="form-control" name="title" placeholder="Image Title" />
                    <br />
                    <input type="file" name="imageFile" class="form-control" />
                    <br />
                    <button class="btn btn-primary w-100">Upload</button>
                </form>
            </div>
        </div>
    </main>
</div>

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="/js/site.js?v=BxFAw9RUJ1E4NycpKEjCNDeoSvr4RPHixdBq5wDnkeY"></script>
</html>